spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpabook
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true System.out으로 뿌림
        format_sql: true
        default_batch_fetch_size: 100 # @BatchSize = 100 한 방에 100개 쫙 뽑아옴. 원래라면 whwer order_item_id = ? 이랬을텐데 in으로 100개 땡김

logging.level:
  org.hibernate.SQL: debug  # 하이버네이트가 생성하는(SQL, JPA) 동작들이 로그로 찍혀서 모두 보임.
  org.hibernate.orm.jdbc.bind: trace